server.port= 8093
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=shalomoficial
spring.datasource.password=Arthas487
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=db_shalom_complemento;encrypt=true;trustServerCertificate=true;
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
